var items = new vis.DataSet([
{id: "ledesma", content: createItem("Ledesma","./img/ledesma.png",["https://drive.google.com/open?id=199_ink2tfQnP7mpJy3oU4IJ8JQ9xM3af"]), start: "1830-12-31"},
{id: "ferrocarril_del_oeste", content: createItem("Ferrocarril del Oeste","0",["https://drive.google.com/open?id=0B8EJMhrdDQ3mWDRGZXlGM24ybzQ"]), start: "1857-08-27"},
{id: "semino", content: createItem("Semino","./img/semino.png",["https://drive.google.com/open?id=1gSn0ZAHKcAzaIjlT8raFHHvzPzvIAux5"]), start: "1865-07-02"},
{id: "laboratorios_casasco", content: createItem("Laboratorios Casasco","./img/laboratorios_casasco.png",["https://drive.google.com/open?id=1YlLx3mKSvmpQdII7KnpZP7CnFVpJNuog"]), start: "1876-07-01"},
{id: "cgfsa", content: createItem("CGFSA","./img/cgfsa.png",["https://drive.google.com/open?id=1aLFuaDYv78PpA2ac3NLimQPR3W2_y8b2"]), start: "1877-04-10"},
{id: "aguila_saint", content: createItem("Aguila Saint","./img/aguila_saint.png",["https://drive.google.com/file/d/1Tu6WJccf0Mv2lhTLfrJL9wp_nLtFBwzI/view?usp=sharing"]), start: "1880-07-01"},
{id: "hesperdina", content: createItem("Hesperdina","./img/hesperdina.png",["https://drive.google.com/open?id=1BEpuZGRxC_jMZorOT844U1i_ksJ6XzqE"]), start: "1880-07-14"},
{id: "rigolleau", content: createItem("Rigolleau","./img/rigolleau.png",["https://drive.google.com/open?id=1TVmcBWVoxLagBQoPupx_clszfKyk12BF"]), start: "1882-03-25"},
{id: "alpargatas", content: createItem("Alpargatas","0",["https://drive.google.com/open?id=1O9jsqaPcduQq4hcyB-j4U2A5_uPilS4d","https://drive.google.com/open?id=18Z6sNfTswZM45vVzMdFoQjTJyKX7pYkA","https://drive.google.com/open?id=1eAY7FMmt8iMdM3C4sSHRAx9Sq8pXkA4c","https://drive.google.com/open?id=1iV-vSbvNE8vCh3VgBXBoNs8mkNlQjAjr"]), start: "1883-07-01"},
{id: "frigorifico_anglo", content: createItem("Frigorífico Anglo","0",["https://drive.google.com/open?id=1RyDin7_R-LJwk7uytRFn2v17DktwL4hl"]), start: "1883-07-01"},