var items = new vis.DataSet([
{id: "2013_13_marzo_designacion_de_jorge_", content: "2013 13 marzo Designación de Jorge Bergoglio como Papa Francisco", image:"../img/informacion.svg", links:["http://drive.google.com/uc?export=view&id=1_nHvC3fZicccBxUlTJsHULNnoP_cCT2I","http://drive.google.com/uc?export=view&id=1_nHvC3fZicccBxUlTJsHULNnoP_cCT2I"], start: new Date(2013,3,13)},
{id: "2011_28_octubre_cepo_cambiario.pd", content: "2011 28 octubre 'Cepo' cambiario", image:"../img/informacion.svg", links:["http://drive.google.com/uc?export=view&id=1M2hhJ7nsn_KH9P2-qvZeDKV80pIaNnDC","http://drive.google.com/uc?export=view&id=1M2hhJ7nsn_KH9P2-qvZeDKV80pIaNnDC"], start: new Date(2011,10,28)},
{id: "2009_1_noviembre_entra_en_vigencia_", content: "2009 1 noviembre Entra en vigencia la Asignación Universal por Hijo", image:"../img/informacion.svg", links:["http://drive.google.com/uc?export=view&id=1ExgA8bHyFzpnStTUwpNNdFJtcKwewQ-3","http://drive.google.com/uc?export=view&id=1ExgA8bHyFzpnStTUwpNNdFJtcKwewQ-3"], start: new Date(2009,11,1)},
{id: "2005_15_diciembre_discurso_de_nesto", content: "2005 15 diciembre Discurso de Nestor Kirchner sobre el pago de la deuda externa", image:"../img/informacion.svg", links:["http://drive.google.com/uc?export=view&id=1Yy3R7mgS3fkSx6T34Iwx7If7vmse8Agh","http://drive.google.com/uc?export=view&id=1Yy3R7mgS3fkSx6T34Iwx7If7vmse8Agh"], start: new Date(2005,12,15)},
{id: "2014_19_agosto_cristina_anuncia_pag", content: "2014 19 agosto Cristina anuncia pago soberano de la deuda externa", image:"../img/informacion.svg", links:["http://drive.google.com/uc?export=view&id=1HMxV_pXbshJxXidyURHRAeDJ-h7S0wMa","http://drive.google.com/uc?export=view&id=1HMxV_pXbshJxXidyURHRAeDJ-h7S0wMa"], start: new Date(2014,8,19)},
{id: "2004_tren_de_levitacion_magnetica_e", content: "2004 Tren de levitación magnética en Shangai", image:"../img/informacion.svg", links:["http://drive.google.com/uc?export=view&id=1_p4R_uH7CPu26Eb9jMCy95pCWnenLGwl","http://drive.google.com/uc?export=view&id=1_p4R_uH7CPu26Eb9jMCy95pCWnenLGwl"], start: new Date(2004,0,0)},
{id: "2009_7_jul_amado_boudou_asume_el_mi", content: "2009 7 jul Amado Boudou asume el Ministerio de Economía (hasta 10 11 2011)", image:"../img/informacion.svg", link:"http://drive.google.com/uc?export=view&id=1pmaJb1GIT4-MHTOEUmk2NAK9P0AK1aj3", start: new Date(2009,7,7)},
{id: "2008_24_nov_turismo_werner_toma_la_", content: "2008 24 nov TURISMO Werner toma la decisión de construir el Ovnipuerto en Cachi Salta", image:"../img/informacion.svg", link:"http://drive.google.com/uc?export=view&id=157PnD0N8YYG7Big_u2EZfdoCaYV6QA8S", start: new Date(2008,11,24)},
{id: "2009_21_dic_redrado_y_las_ri.pdf", content: "2009 21 dic Redrado y las RI", image:"../img/informacion.svg", link:"http://drive.google.com/uc?export=view&id=1shOv9ASak9BlboMBX4J_q3NZD_aBq5QL", start: new Date(2009,12,21)},
{id: "2008_11_mar_resolucion_125_que_inic", content: "2008 11 mar Resolución 125 que inicia el conflicto con el campo", image:"../img/informacion.svg", link:"http://drive.google.com/uc?export=view&id=1eavq--bQ0WhCq53PhqoorRF0lGEW1CQ7", start: new Date(2008,3,11)},
{id: "2013_5_mar_fallecimiento_de_hugo_ch", content: "2013 5 mar Fallecimiento de Hugo Chávez", image:"../img/informacion.svg", link:"http://drive.google.com/uc?export=view&id=15Cj9Vwpl3eph69zCv4kwdB9hSbIBXins", start: new Date(2013,3,5)},
{id: "2008_21_ene_crisis_internacional_en", content: "2008 21 ene Crisis internacional en EEUU", image:"../img/informacion.svg", link:"http://drive.google.com/uc?export=view&id=1wfYkZt2iLotXrqgCl6ek8IXrg1tObBzK", start: new Date(2008,1,21)},
{id: "2006_3_ene_cancelacion_de_la_deuda_", content: "2006 3 ene Cancelación de la deuda con el FMI de Argentina", image:"../img/informacion.svg", link:"http://drive.google.com/uc?export=view&id=1LvfZqBX7Ajuwn0F3Ql0Twdu4RS55eGEc", start: new Date(2006,1,3)},
{id: "2003_25_may_presidencia_de_nestor_k", content: "2003 25 may Presidencia de Néstor Kichner", image:"../img/informacion.svg", link:"http://drive.google.com/uc?export=view&id=1sUXncg9DOJfp2u8c_CJ8yyeeKiXH_j-l", start: new Date(2003,5,25)},
{id: "2009_14_dic_creacion_del_fondo_del_", content: "2009 14 dic Creación del Fondo del Bicentenario", image:"../img/informacion.svg", link:"http://drive.google.com/uc?export=view&id=1nAnYTD4GGrR8sfS-iM9zIwXHGvxAqZAr", start: new Date(2009,12,14)},
{id: "2007_10_dic_primera_presidencia_de_", content: "2007 10 dic Primera Presidencia de Cristina Fernandez de Kirchner", image:"../img/informacion.svg", link:"http://drive.google.com/uc?export=view&id=1wSu4S-WTuFMGs-w3kTza6YA79gW6n46M", start: new Date(2007,12,10)},
{id: "2008_15_set_crisis_financiera_inter", content: "2008 15 set Crisis financiera internacional 2008", image:"../img/informacion.svg", link:"http://drive.google.com/uc?export=view&id=14eQnmjniC8NNe7h-tYQDEqVGntgU4dWF", start: new Date(2008,9,15)}
]);